### ISSUE TITLE
Add support to .NET 8

### ISSUE THREAD

**Issue by ernstc** [ernstc/YaccLexTools#5]

**Comment by ernstc** [comment]
Resolved in release v1.2.2

**Comment by springcomp** [comment]
@ernstc  please consider publishing a .net 8.0-compatibe NuGet package 🙏

**Comment by ernstc** [comment]
Hi @springcomp, can you give more details about your issue?
It is already compatible with .NET 8 and .NET 9.

**Comment by springcomp** [comment]
Thanks for the feedback @ernstc  I seem to have tried the latest version and it failed with a missing .NET 6 runtime.
I must have made a mistake.
Let me retry.
